# Configuration for welcome messaging - https://github.com/behaviorbot/welcome


# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request to sign the CLA!.
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! Welcome to Brackets Community (brackets.io).
# It is recommend to include as many gifs and emojis as possible

updateDocsComment: >
  Thanks for opening this pull request and contributing to Brackets Community! 